{
 "title": "Gateway Monitor Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Gateway Uptime (Last 7 Days)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(gateway_link_status{gateway_name='Gw1'}[1w]) * 100",
     "legendFormat": "Gw1 uptime"
    }
   ]
  },
  {
   "title": "Gateway Status History",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (gateway_name)(gateway_link_status)\r\n\r\n"
    }
   ]
  },
  {
   "title": "Gateway Geomap",
   "type": "geomap",
   "gridPos": { "h": 21, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "up{job='gateway_link_status'}" }
   ]
  }
 ]
}