services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards  
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitor-net

  go-backend:
    build:
      context: ./go-backend
      dockerfile: Dockerfile
    ports:
      - "9100:9100"
    networks:
      - monitor-net
    depends_on:
      - prometheus

networks:
  monitor-net:
